CENTER_NAME: 'ENA'
ANALYSIS_USERNAME:
ANALYSIS_PASSWORD:
PIPELINE_NAME: 'Nanopore Analysis Workflow'
PIPELINE_VERSION: '1.0.0'
SUBMISSION_TOOL: 'ena-analysis-submitter'
SUBMISSION_TOOL_VERSION: '1.0.0'
ACTION: 'ADD'